---
- hosts: all
  sudo: yes
  roles:
    - yaegashi.blockinfile

- hosts: tag_cluster_tag_couchbase_ansible
  roles:
    - discover_os_family

- hosts: os_Debian
  sudo: yes
  roles:
    - couchbase_nodes_setup_debian
    - couchbase_nodes_setup

- hosts: os_RedHat
  sudo: yes
  roles:
    - couchbase_nodes_setup_redhat
    - couchbase_nodes_setup