---

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - amazon_nodes_creation

- hosts: tag_cluster_tag_couchbase_ansible
  roles:
    - discover_os_family

- hosts: os_Debian
  roles:
    - couchbase_nodes_setup_debian
    - couchbase_nodes_setup

- hosts: os_RedHat
  roles:
    - couchbase_nodes_setup_redhat
    - couchbase_nodes_setup

- hosts: tag_Name_couchbase_ansible_main
  roles:
    - discover_os_family_of_main_node

- hosts: main_node_os_Debian
  roles:
    - couchbase_clusterizing

- hosts: main_node_os_RedHat
  roles:
    - couchbase_clusterizing
