---

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - amazon_nodes_creation

- hosts: tag_cluster_tag_couchbase_ansible
  # user: ec2-user
  user: ubuntu
  roles:
    - couchbase_nodes_setup

- hosts: tag_Name_couchbase_ansible_main
  # user: ec2-user
  user: ubuntu
  roles:
    - couchbase_clusterizing
