---
- include: tune_system.yml

- name: download Couchbase package
  get_url: "url=http://packages.couchbase.com/releases/3.0.1/couchbase-server-community_3.0.1-ubuntu12.04_amd64.deb
            dest=~/couchbase-server-community_3.0.1-ubuntu12.04_amd64.deb"
  sudo: no

- name: Install dependencies
  apt: name=openssl state=present
  sudo: no

- name: Install Couchbase .deb file on all machines
  apt: deb=/home/ubuntu/couchbase-server-community_3.0.1-ubuntu12.04_amd64.deb

- name: Create file system on EBS volume
  filesystem:
    fstype: ext4
    dev: "/dev/xvdf"

- name: Mount EBS volume
  mount:
    name: /mnt/couchbase-data
    fstype: ext4
    src: /dev/xvdf
    state: mounted