---
# TODO : association avec route 53, add login password, centos

- name: Make couchbase owner of EBS volume
  file: path=/mnt/couchbase-data group=couchbase owner=couchbase mode=0744 state=directory

- name: Start couchbase-server
  service: name=couchbase-server state=started

- name: Wait for Couchbase API availability on nodes
  wait_for: delay=3 timeout=60 port=8091

- name: Check data storage configuration
  shell: "/opt/couchbase/bin/couchbase-cli server-info -c localhost:8091 -u {{ couchbase_username }} -p {{ couchbase_password }}"
  register: couchbase_config_json

- set_fact:
   couchbase_config: "{{ couchbase_config_json.stdout|from_json }}"

- name: Configure Couchbase to use EBS volume
  shell: "sudo /opt/couchbase/bin/couchbase-cli node-init -c localhost:8091 -u {{ couchbase_username }}
  -p {{ couchbase_password }} --node-init-data-path=/mnt/couchbase-data --node-init-index-path=/mnt/couchbase-data"
  when: '"/mnt/couchbase-data" not in couchbase_config.availableStorage.hdd|to_json'
